import subprocess
import time
print("--------------------------------------")
print("            BlackArch     By:KattStof")
print("            Install       v:1.0.0    ")
print("            Script                ")
print("--------------------------------------")
print(" ")
print (" ")
print ("[1] Install All Blackarch *This will take a while go drink some coffee*")
print("[2] Install certain Blackarch Tool")
print ("[0] Exit")
spam = input(":")
if spam == '1':
        print("-------------------------------------")
        print("INSTALLING AND EXECUTING STRAP.SH     ")
        print("PLEASE WAIT.........                   ")
        print("--------------------------------------")
        time.sleep(3)
        subprocess.call("curl -O https://blackarch.org/strap.sh", shell=True)
        subprocess.call("sudo chmod +x strap.sh", shell=True)
        subprocess.call("sudo ./strap.sh", shell=True)
        subprocess.call("sudo pacman -S blackarch", shell=True)
if spam == '2':
        print("------------------------------------")
        print("INSTALLING AND EXECUTING STRAP.SH    ")
        print("PLEASE WAIT.......                  ")
        print("------------------------------------")

        time.sleep(3)
        subprocess.call("curl -O https://blackarch.org/strap.sh", shell=True)
        subprocess.call("sudo chmod +x strap.sh", shell=True)
        subprocess.call("sudo ./strap.sh", shell=True)
        eggs = input("Which tool would you like to install?:")
        subprocess.call("sudo pacman -S "  + eggs, shell=True)
if spam == '0':
        print("If you do not go get us a shrubbery we shall nee you again")
        time.sleep(1)
        print("...one that looks good")
        time.sleep(1)
        print("...but not too expensive")
        exit()
